### ISSUE TITLE
Add more support for common tilde characters (solution provided)

### ISSUE THREAD

**Issue by rrfeup** [SacBase/publistf#3]
The characters **"ã"**, **"õ"** and their corresponding capitals are very common in names in some languages (namely portuguese). Currently they are not being sanitized and their form **"\\~a"** just replaces the tilde for a space and leaves the "a" character. 

This can be solved using the same method that is already being used for **"ñ"**: adding the following lines to the `$search_array` and `$replace_array` in **sanitizer.php**:

```
    $search_array = array(
        ...
        '\~a',
        '\~A',
        '\~o',
        '\~O',
        ...
    );
    $replace_array = array(
        ...
	'ã',
	'Ã',
	'õ',
	'Õ',
        ...
    );
```

I am sure this will be handy for many users, and hope you can release an updated version.

Thanks in advance.

**Comment by hv15** [comment]
hi @rrfeup, I've incorporated your suggestion into the [1.1.0 release](https://github.com/SacBase/publistf/releases/tag/1.1.0). Let me know if this works for you. I've also updated the dokuwiki plugin listing, so you should be able to use the extension manager to update...

**Comment by rrfeup** [comment]
Hi, @hv15. 

First of all, thanks for the quick turnaround. 

There was some problem: "ã" were ok, but some of the others were not. I checked the file, and noticed that in lines 29-30, the `'\~e', '\~E'` are missing, which mismatches with lines 47-49, and this offsets the remaining characters' replacement. 

https://github.com/SacBase/publistf/blob/9c7284eefd45f4d1cc96b5697461ecfdc6b847d3/sanitiser.php#L29-L31

https://github.com/SacBase/publistf/blob/9c7284eefd45f4d1cc96b5697461ecfdc6b847d3/sanitiser.php#L47-L50

Can you please take a look? Thanks in advance.

**Comment by hv15** [comment]
oops, well spotted! I've fixed this, checkout the latest release.

**Comment by rrfeup** [comment]
Hi. 

It seems to be ok now.

(side note: the extension manager did not notify as an update, I believe it was due to the version number being unchanged; I assume that you decided to keep it as version 1.1.0)

Thanks again for the quick intervention.

All the best
