### ISSUE TITLE
Call signature in syntax_plugin_publistf "handle" and "render" not compatible with "Hogfather" RC2

### ISSUE THREAD

**Issue by todmorrison** [SacBase/publistf#4]
I just upgraded to Release rc2-2020-06-01 "Hogfather" RC2 and had to change the syntax_plugin_publistf handle and render functions to pass Doku_Handler by value rather than by reference to avoid an error, i.e.

I changed:

function handle($match, $state, $pos, &$handler)

to

function handle($match, $state, $pos, $handler)

and

function render($mode, &$renderer, $data)

to

function render($mode, $renderer, $data)

**Comment by hv15** [comment]
Thanks @todmorrison! I did a quick test, and your suggested changes seem to work fine with my copy of DokuWiki. I've made a new release (035299a6f2a74f9ee464f07fe9209bf710caa3e1) and published this on dokuwiki.org.

**Comment by hv15** [comment]
closing, assumed fixed through previously mentioned commit
